import sys
input0 = input('1.Would you rather have your flight delayed by 8 hours or lose your luggage? : ')
input1 = input('2.Would you rather be in jail for a year or lose a year off your life? : ')
input2 = input('3.Would you rather be forced to dance every time you heard music or be forced to sing along to any song you heard? : ')
input3 = input('4.Would you rather have whatever you are thinking to appear above your head for everyone to see or have absolutely everything you do live streamed for anyone to see? : ')
input4 = input('5.Would you rather live until you are 200 but look like you are 200 the whole time even though you are healthy or look like you are 25 all the way until you die at age 65? : ')
input5 = input('6.Would you rather be a reverse centaur or a reverse mermaid/merman? : ')
input6 = input('7.Would you rather your only mode of transportation be a donkey or a giraffe? : ')
input7 = input('8.Would you rather every shirt you ever wear be kind of itchy or only be able to use 1 ply toilet paper?')
input8 = input('9.Would you rather have to read aloud every word you read or sing everything you say out loud? : ')
input9 = input('10.Would you rather be unable to move your body every time it rains or not be able to stop moving while the sun is out? : ')
break0 = input('Do you want to stop or continue : ')
if break0 == 'I want to stop': 
    print('Bye! Hope you enjoyed the game!')
    sys.exit()
else:
    print('Hope your having fun! If you chose the 1st for 1, 2nd for 2, 1st for 3, 1st for 4, 2nd for 5, 1st for 6, 2nd for 7, 1st for 8, 2nd for 9, and 2nd for 10, or some of those, your like me! I chose those for  my answers!')
    input10 = input('1.Would you rather be compelled to high five everyone you meet or be compelled to give wedgies to anyone in a green shirt? : ')
    input11 = input('2.Would you rather have all dogs try to attack you or all birds try to attack you when they see you? : ')
    input12 = input('3.Would you rather have skin that changes color based on your emotions or tattoos appear all over your body depicting what you did yesterday? : ')
    input13 = input('4.Would you rather there be a perpetual water balloon war going on in your city/town or a perpetual food fight? : ')
    input14 = input('5.Would you rather become twice as strong when both of your fingers are stuck in your ears or crawl twice as fast as you can run? : ')
    input15 = input('6.Would you rather have everything you draw become real but be permanently terrible at drawing or be able to fly but only as fast as you can walk? : ')
    input16 = input('7.Would you rather vomit uncontrollably for one minute every time you hear the happy birthday song or get a headache that lasts for the rest of the day every time you see a bird (including in pictures or a video)? : ')
    input17 = input('8.Would you rather be lost in a bad part of town or lost in the forest? : ')
    input18 = input('9.Would you rather give up watching TV/movies or playing games for a year?')
    input19 = input('10.Would you rather lose your best friend or all of your friends except for your best friend? : ')
    input20 = input('11.Would you rather live in a small house with furniture, or a big house with no furniture? : ')
    break1 = input('Do you want to stop or continue : ')
if break1 == 'I want to stop': 
    print('Bye! Hope you enjoyed the game!')
    sys.exit()
else:
    print('Hope your having fun! If you chose the 1st for 1, 2nd for 2, 1st for 3, 1st for 4, 2nd for 5, 2nd for 6, 2nd for 7, 2nd for 8, 2nd for 9, 2nd for 10, and 1st for 11, or some of those, your like me! I chose those for my answers!')
    input21 = input('1.Would you rather eat an egg with a half-formed chicken inside or eat ten cooked grasshoppers? : ')
    input22 = input('2.Would you rather be the absolute best at something that no one takes seriously or be well above average but not anywhere near the best at something well respected? : ')
    input23 = input('3.Would you rather sleep 2 years straight or sleep 8 minutes daily? : ')
    input24 = input('4.Would you rather have constantly dry eyes or a constant runny nose? : ')
    input25 = input('5.Would you rather have out of control body hair or a strong, pungent body odor? : ')
    input26 = input('6.Would you rather clean rest stop toilets or work in a slaughterhouse for a living? : ')
    input27 = input('7.Would you rather not be able to see anything or have mild but constant ringing in the ears? : ')
    input28 = input('8.Would you rather have chapped lips that never heal or terrible dandruff that can’t be treated? : ')
    input29 = input('Would you rather be alone for the rest of your life or always be surrounded by annoying people? : ')
    input30 = input('9.Would you rather never use social media sites/apps again or never watch another movie or TV show? : ')
    break2 = input('Do you want to stop or continue : ')
if break2 == 'I want to stop': 
    print('Bye! Hope you enjoyed the game!')
    sys.exit()
else:
    print('Hope your having fun! If you chose the 1st for 1, 2nd for 2, 1st for the 3, 2nd for 4, 1st for 5, 1st for 6, 2nd for 7, 2nd for 8, and 2nd for 9, or some of those, your like me! I chose those for my answers!')
    input31 = input('1.Would you rather be put in a maximum-security federal prison with the hardest of the hardened criminals for one year or be put in a relatively relaxed prison where wall street types are held for ten years? : ')
    input32 = input('2.Would you rather wake up in the middle of an unknown desert or wake up in a rowboat on an unknown body of water? : ')
    input33 = input('3.Would you rather walk around work or school for the whole day without realizing there is a giant brown stain on the bak of your pants or realize the deadline for that important paper/project was yesterday, and you are nowhere near done? : ')
    input34 = input('4.Would you rather be hired for a well-paying job that you lied to get and have no idea how to do or be about to give the most important presentation of your life but you can’t remember any of the material you prepared? : ')
    input35 = input('5.Would you rather be feared by all or loved by all? : ')
    input36 = input('6.Would you rather sell all of your possessions or sell one of your organs? : ')
    input37 = input('7.Would you rather be reincarnated as a fly or just cease to exist after you die? : ')
    input38 = input('8.Would you rather know the uncomfortable truth of the world or believe a comforting lie? : ')
    input39 = input('9.Would you rather die in 20 years with no regrets or die in 50 years with many regrets? : ')
    input40 = input('10.Would you rather go to jail for 4 years for something you didn’t do or get away with something horrible you did but always live in fear of being caught? : ')
    print('I hope you had fun!! If you chose the 1st for 1, 2nd for 2, 2nd for 3, 2nd for 4, 2nd for 5, 1st for 6, 2nd for 7, 1st for 8, 1st for 9, 1st for 10, or some of those, your like me! I chose those for my answers! You can compare answers with your friend. PS: If your friend is not here now, you can play these on your friend! Maybe you can make a fun game out of it! Try out this game with your friend! PS: See their reaction! It will be fun!')