
name = input('Enter your name')
silly_word = input('enter a silly word')
number = input('Enter a number')
adjective = input('Enter an adjective')
noun = input('Enter a noun')
adjective1 = input('Enter an adjective')
relative = input('Enter a relative')
adjective2 = input('Enter an adjective')
verb = input('Enter a verb')
adjective3 = input('Enter an adjective')
adjective4 = input('Enter an adjecive')

# string concatenation
print('Hello my name is astronaut ' + name)
print('I am on my way to ' + silly_word)
print('I will be gone for ' + number + 'days. ')
print('I am very ' + adjective + 'about the trip, but I will miss my ' + noun + '. ')
print('I have heard that the atmosphere there is ' + adjective1 + '. ')
print('Luckily my ' + relative + ' packed me a jacket to keep me ' +  adjective2 + '. ')
print('When I land on the planet I will ' + verb + ' for joy. ')
print('I am ' + adjective3 + ' to walk on another planet. ')
print('I could not be more ' + adjective4 + ' for this trip! ')