noun = input('Enter a noun : ')
plural = input('Enter a plural noun : ')
print("Today every student has a computer small enough to fit in his " + noun + ". He can solve any problem by simply pushing the computers little " + plural + " .")
plural_noun = input('Enter a plural noun : ')
verb_present_tense = input('Enter a present tense verb : ')
print("Computers can add, multiply, divide, and " + plural_noun + ". They can also " + verb_present_tense + " better than a human.")
part_of_body_present_tense = input('Enter a present tense in a part of the body : ')
adjective = input('Enter a adjective : ')
plural_noun1 = input('Enter another plural noun : ')
adjective1 = input('Enter another adjective : ')
print("Others have a " + adjective + " screen that shows all kinds of " + plural_noun1 + " and " + adjective1 + " figures.")